### PR TITLE
Create a youtube clone

### PR DESCRIPTION
**Pull request by kagaramag**
- Create HTML page that looks like youtube
- Style the page and make it responsive

### CODE REVIEW

**Review by fatymahmed — COMMENTED** [review]
## Hi @djallas  @Genius8 👋
Your project looks neat, great job on that 👏👏, however, there are a few things that you need to fix.

**General**
- You've committed DS_Store which you shouldn't have, fix this by adding it to the .gitignore file [see the screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png). After adding it to .gitignore, you'll have to remove it from cache, check [this](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore) on how to do it.

- Your HTML markup file has some errors, according to the requirements, you should check HTML markup with this validator https://validator.w3.org/#validate_by_upload. [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png), please fix those.

Your HTML file has an error
Screenshot

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes and request for another code review.

## Status: Changes Required

_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help_

**Comment by kagaramag** [comment]
We worked on feedback given by @fatymahmed

**Review by fatymahmed — APPROVED** [review]
## Hi @djallas @Genius8 
Great job on making the changes 👏👏
Your project looks good and it's an approval 👍  from me
You may go ahead and merge the pull request.

## Status: Approved
_Don't forget to fill out the project completion form_

**Pull request merged**
